samples: config/samples.tsv

suffix: .fastq.gz

# The root argument tells you where the genome will be located
# on the local system. All other arguments are required for
# downloading
ref:
  build: GRCh37
  genbank: GCA_000001405.1
  gencode: 33
  assembly: primary_assembly
  root: ../refs

# Given we only have 50nt reads, don't group during fastqc
fastqc:
  params: "--nogroup --noextract"

# Settings for AdapterRemoval
trimming:
  ## NEB Next Kit https://www.biostars.org/p/149301/
  adapter1: CAAGCAGAAGACGGCATACGAGATNNNNNNGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT
  adapter2: AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT
  maxns: 1
  minlength: 35
  minqual: 30

# Settings for HicPro
hicpro:
  ncpu: 10
  sort_ram: 1000M
  pair1_ext: _1
  pair2_ext: _2
  # Not defined in the paper. Assumed to be MboI
  enzyme: MboI
  phred: 33
  min_mapq: 0
  ligation_site: GATCGATC
  restriction_site: mboi
  bin_size: 5000 10000 20000 40000 100000
  matrix_format: upper

